controllers/cliente_controller.py
from flask import Blueprint, request, redirect, url_for
from core.database import db
from models.cliente_model import Cliente
from views import cliente_view
from config.security import requiere_admin

cliente_bp = Blueprint("cliente", __name__, url_prefix="/clientes")

@cliente_bp.route("/")
def index():
    clientes = Cliente.get_all()
    return cliente_view.list(clientes)

@cliente_bp.route("/create", methods=["GET", "POST"])

def create():
    if request.method == "POST":
        nombre = request.form["nombre"]
        email = request.form.get("email")
        telefono = request.form.get("telefono")
        direccion = request.form.get("direccion")

        nuevo = Cliente(nombre, email, telefono, direccion)
        nuevo.save()
        return redirect(url_for("cliente.index"))

    return cliente_view.create()

@cliente_bp.route("/edit/<int:id>", methods=["GET", "POST"])

def edit(id):
    cliente = Cliente.get_by_id(id)
    if request.method == "POST":
        nombre = request.form["nombre"]
        email = request.form.get("email")
        telefono = request.form.get("telefono")
        direccion = request.form.get("direccion")
        cliente.update(nombre, email, telefono, direccion)
        return redirect(url_for("cliente.index"))

    return cliente_view.edit(cliente)

@cliente_bp.route("/delete/<int:id>")
@requiere_admin
def delete(id):
    cliente = Cliente.get_by_id(id)
    cliente.delete()
    return redirect(url_for("cliente.index"))

views/cliente_view.py
from flask import render_template

def list(clientes):
    return render_template("clientes/index.html", clientes=clientes)

def create():
    return render_template("clientes/create.html")

def edit(cliente):
    return render_template("clientes/edit.html", cliente=cliente)

templates/clientes/create.html
{% extends 'base.html' %}
{% block title %}Crear Cliente{% endblock %}
{% block content %}
<h2>Crear Cliente</h2>
<form method="POST">
    <div class="mb-3">
        <label>Nombre</label>
        <input type="text" name="nombre" class="form-control" required>
    </div>
    <div class="mb-3">
        <label>Email</label>
        <input type="email" name="email" class="form-control">
    </div>
    <div class="mb-3">
        <label>Teléfono</label>
        <input type="text" name="telefono" class="form-control">
    </div>
    <div class="mb-3">
        <label>Dirección</label>
        <input type="text" name="direccion" class="form-control">
    </div>
    <button type="submit" class="btn btn-success">Guardar</button>
</form>
{% endblock %}

templates/clientes/edit.html
{% extends 'base.html' %}
{% block title %}Editar Cliente{% endblock %}
{% block content %}
<h2>Editar Cliente</h2>
<form method="POST">
    <div class="mb-3">
        <label>Nombre</label>
        <input type="text" name="nombre" class="form-control" value="{{ cliente.nombre }}" required>
    </div>
    <div class="mb-3">
        <label>Email</label>
        <input type="email" name="email" class="form-control" value="{{ cliente.email }}">
    </div>
    <div class="mb-3">
        <label>Teléfono</label>
        <input type="text" name="telefono" class="form-control" value="{{ cliente.telefono }}">
    </div>
    <div class="mb-3">
        <label>Dirección</label>
        <input type="text" name="direccion" class="form-control" value="{{ cliente.direccion }}">
    </div>
    <button type="submit" class="btn btn-success">Actualizar</button>
</form>
{% endblock %}

templates/clientes/index.html
{% extends 'base.html' %}
{% block title %}Clientes{% endblock %}
{% block content %}
<h2>Clientes</h2>

<a href="{{ url_for('cliente.create') }}" class="btn btn-light mb-4 text-primary shadow-sm rounded-pill">
    <i class="bi bi-plus-circle" ></i> Crear Cliente
</a>

<div class="card shadow-lg border-0 glass-card">
    <div class="card-body">
        <div class="table-responsive">
        <table id="tablaUsuarios"class="table table-striped table-hover align-middle text-center text-dark w-100">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Teléfono</th>
                <th>Dirección</th>
                <th>Acciones</th>
            </tr>
        </thead>
    <tbody>
        {% for c in clientes %}
        <tr>
            <td>{{ c.id }}</td>
            <td>{{ c.nombre }}</td>
            <td>{{ c.email }}</td>
            <td>{{ c.telefono }}</td>
            <td>{{ c.direccion }}</td>
            <td>
                
                <a href="{{ url_for('cliente.edit', id=c.id) }}" class="btn btn-warning btn-sm rounded-pill px-3 me-2">
                    <i class="bi bi-pencil-square"></i>Editar</a>
                {% if session.get('usuario_rol') == 'admin' %}
                <a href="{{ url_for('cliente.delete', id=c.id) }}"class="btn btn-danger btn-sm rounded-pill px-3" onclick="return confirm('¿Seguro que deseas eliminar este usuario?')"><i class="bi bi-trash3"></i>Eliminar</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script src="/static/js/usuarios_datatable.js"></script>
{% endblock %}